# Generated by Django 5.1.3 on 2024-12-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("student", "学生"), ("teacher", "教师")],
                default="student",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
